# Generated by Django 5.2.5 on 2025-08-08 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('1', 'Agendado'), ('2', 'Concluído'), ('3', 'Cancelado')], default='1', max_length=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.customer')),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.professional')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.service')),
            ],
            options={
                'indexes': [models.Index(fields=['date_time', 'status'], name='idx_schedule_data_status')],
                'unique_together': {('date_time', 'professional')},
            },
        ),
    ]
